// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EmployeeManagement.Models;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(NTT_DBContext))]
    [Migration("20200427130733_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NttDataEmployee.Models.NttEmployeeRecords", b =>
                {
                    b.Property<int>("NttEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("NttEmployeeId")
                        .HasName("PK__Ntt_Empl__EE5518D92A8BFB6D");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasName("UQ__Ntt_Empl__7AD04F1062787924");

                    b.ToTable("Ntt_Employee_Records");
                });

            modelBuilder.Entity("NttDataEmployee.Models.NttEmployeeTimeDetails", b =>
                {
                    b.Property<int>("EmployeeTimeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeTImeDetailId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NttEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("datetime");

                    b.HasKey("EmployeeTimeDetailId")
                        .HasName("PK__Ntt_Empl__CEF11F0DEA8B01DC");

                    b.ToTable("Ntt_Employee_Time_Details");
                });

            modelBuilder.Entity("NttDataEmployee.Models.NttRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("RoleId")
                        .HasName("PK__Ntt_Role__8AFACE1A903E4BA5");

                    b.ToTable("Ntt_Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
